// components/SearchBar.jsx
import React, { useContext, useEffect, useState } from 'react'
import { ShopContext } from '../context/ShopContext'
import { assets } from '../plugins/assets';
import { useLocation } from 'react-router-dom';

const SearchBar = () => {

    const{ search, setSearch, showSearch, setShowSearch} = useContext(ShopContext);
    const [visible,setVisible] = useState(false);
    const location = useLocation();

    useEffect(()=>{
        if (location.pathname.includes('collection')) {
            setVisible(true);
        }
        else {
            setVisible(false)
        }
    },[location])

  return showSearch && visible ? (
    <div className='border-t border-b bg-grey-50 text-center'>
        <div className='inline-flex items-center justify-center border border-grey-400 px-5 py-2 my-5 mx-3 rounded-full w-3/4 sm:w-1/2'>
            <input value={search} onChange={(e)=>setSearch(e.target.value)} className='flex-1 outline-none bg-inherit text-sm' type="text" placeholder='Search'/>
            <img className='w-4' src={assets.search_icon} alt="" />
        </div>
        <img onClick={()=>setShowSearch(false)} className='inline w-3 cursor-pointer' src={assets.cross_icon} alt="" />
    </div>
  ) : null
}

export default SearchBar

// components/SearchBar.vue
<template>
    <div v-if="showSearch && visible" class="border-t border-b bg-grey-50 text-center">
      <div class="inline-flex items-center justify-center border border-grey-400 px-5 py-2 my-5 mx-3 rounded-full w-3/4 sm:w-1/2">
        <input
          v-model="search"
          class="flex-1 outline-none bg-inherit text-sm"
          type="text"
          placeholder="Search"
        />
        <img class="w-4" :src="assets.search_icon" alt="" />
      </div>
      <img
        @click="setShowSearch(false)"
        class="inline w-3 cursor-pointer"
        :src="assets.cross_icon"
        alt=""
      />
    </div>
  </template>
  
  <script>
  import { ref, watch, inject } from 'vue';
  import { useRoute } from 'vue-router';
  import { ShopContext } from '../context/ShopContext'; // Adjust the import according to your context path
  import { assets } from '../plugins/assets'; // Adjust the import according to your assets path
  
  export default {
    setup() {
      const { search, setSearch, showSearch, setShowSearch } = inject(ShopContext);
      const visible = ref(false);
      const route = useRoute();
  
      watch(route, (newRoute) => {
        visible.value = newRoute.path.includes('collection');
      });
  
      return {
        search,
        setSearch,
        showSearch,
        setShowSearch,
        visible,
        assets,
      };
    },
  };
  </script>
  
  <style scoped>
  /* Add any styles specific to this component here */
  </style>
